export const CATEGORIES = [
  {
    slug: 'flooring',
    longDesc: 'Whether you\'re tiling a new house, replacing old floors or installing epoxy in a garage, flooring is the highest-impact upgrade a Sri Lankan home can get. TilersHub lists verified floor tiling specialists, parquet and laminate installers, and epoxy contractors across all 25 districts. Compare experience and reviews, then contact directly on WhatsApp — labour rates currently run Rs. 100–250 per sq.ft depending on tile size.',
    label: 'Flooring Services',
    icon: '⬜',
    color: '#2563EB',
    bg: '#EFF6FF',
    border: '#BFDBFE',
    count: 10,
    desc: 'Find verified flooring specialists across Sri Lanka — floor tiling, epoxy, parquet, vinyl and more.',
    terms: ['floor', 'tiling', 'tile', 'mosaic', 'epoxy', 'parquet', 'laminate', 'vinyl', 'granite', 'staircase'],
    blogSlugs: ['large-format-tiles-guide', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'bathroom',
    longDesc: 'Bathrooms are the most technically demanding room in a Sri Lankan home — poor waterproofing is the #1 cause of renovation failure within 2–3 years. TilersHub connects you with verified bathroom renovators, plumbers and waterproofing specialists who follow proper membrane and screed practice. Post your project free and compare itemised quotes before committing.',
    label: 'Bathroom Services',
    icon: '🚿',
    color: '#0369a1',
    bg: '#e0f2fe',
    border: '#7dd3fc',
    count: 7,
    desc: 'Bathroom renovation, plumbing, waterproofing and fittings by verified specialists.',
    terms: ['bathroom', 'bath', 'shower', 'vanity', 'plumbing', 'waterproof', 'mirror'],
    blogSlugs: ['bathroom-renovation-cost-sri-lanka', 'waterproofing-bathroom-guide'],
  },
  {
    slug: 'kitchen',
    longDesc: 'A kitchen renovation combines tiling, cabinetry and splashback work that must be sequenced correctly. The contractors listed here handle pantry cupboard installation, granite worktops and kitchen wall tiling across Sri Lanka. Get multiple WhatsApp quotes free through TilersHub before starting.',
    label: 'Kitchen Services',
    icon: '🍳',
    color: '#2563EB',
    bg: '#EFF6FF',
    border: '#fed7aa',
    count: 2,
    desc: 'Kitchen renovation, cabinet installation and kitchen tile works by experienced contractors.',
    terms: ['kitchen', 'cabinet', 'splashback'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'glass',
    longDesc: 'Glass railings, aluminium doors and windows, gypsum and IPanel ceilings are precision trades where installation quality decides longevity. TilersHub lists verified glass and aluminium fabricators across Sri Lanka with photos of past work — compare and contact directly on WhatsApp.',
    label: 'Glass & Aluminium',
    icon: '🪟',
    color: '#7c3aed',
    bg: '#f5f3ff',
    border: '#ddd6fe',
    count: 6,
    desc: 'Glass railings, aluminium doors & windows, IPanel ceilings and gypsum works.',
    terms: ['glass', 'aluminium', 'aluminum', 'railing', 'ceiling', 'ipanel', 'gypsum', 'gate', 'fencing', 'door', 'window'],
    blogSlugs: ['how-to-choose-a-tiler', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'construction',
    longDesc: 'From roofing and plastering to partition walls and full builds, these verified contractors cover structural and finishing work across Sri Lanka. Post your project on TilersHub to get competing quotes — free, with no commission added to your price.',
    label: 'Construction Services',
    icon: '🏗️',
    color: '#334155',
    bg: '#F8FAFC',
    border: '#E2E8F0',
    count: 9,
    desc: 'Roofing, plastering, partition walls, concrete works and full construction services.',
    terms: ['roof', 'plaster', 'partition', 'water tank', 'concrete', 'masonry', 'carpentry', 'debris', 'demolition', 'cleaning', 'construction'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'outdoor',
    longDesc: 'Outdoor work — landscaping, pool construction, paving and pergolas — needs contractors who understand Sri Lankan monsoon drainage and sun exposure. The specialists listed here have verified profiles and past-project photos. Compare quotes free on TilersHub.',
    label: 'Outdoor Services',
    icon: '🌿',
    color: '#15803d',
    bg: '#f0fdf4',
    border: '#bbf7d0',
    count: 4,
    desc: 'Landscaping, swimming pool construction, paving, driveways and pergola structures.',
    terms: ['outdoor', 'landscape', 'garden', 'pool', 'paving', 'driveway', 'pergola', 'shade'],
    blogSlugs: ['large-format-tiles-guide', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'trades',
    longDesc: 'House painting, electrical wiring, air conditioning, solar and smart-home installation round out any renovation. Every tradesperson listed on TilersHub is reviewed before listing goes live — post your job free and pick from competing WhatsApp quotes.',
    label: 'Trades & More',
    icon: '🎨',
    color: '#c2410c',
    bg: '#EFF6FF',
    border: '#fed7aa',
    count: 9,
    desc: 'House painting, electrical works, air conditioning, solar panels, CCTV and smart home installation.',
    terms: ['paint', 'lighting', 'wiring', 'electrical', 'air condition', 'solar', 'cctv', 'security', 'smart home', 'automation'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
]
