export const CATEGORIES = [
  {
    slug: 'flooring',
    label: 'Flooring Services',
    icon: '⬜',
    color: '#0f766e',
    bg: '#f0fdfa',
    border: '#99f6e4',
    count: 10,
    desc: 'Find verified flooring specialists across Sri Lanka — floor tiling, epoxy, parquet, vinyl and more.',
    terms: ['floor', 'tiling', 'tile', 'mosaic', 'epoxy', 'parquet', 'laminate', 'vinyl', 'granite', 'staircase'],
    blogSlugs: ['large-format-tiles-guide', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'bathroom',
    label: 'Bathroom Services',
    icon: '🚿',
    color: '#0369a1',
    bg: '#e0f2fe',
    border: '#7dd3fc',
    count: 7,
    desc: 'Bathroom renovation, plumbing, waterproofing and fittings by verified specialists.',
    terms: ['bathroom', 'bath', 'shower', 'vanity', 'plumbing', 'waterproof', 'mirror'],
    blogSlugs: ['bathroom-renovation-cost-sri-lanka', 'waterproofing-bathroom-guide'],
  },
  {
    slug: 'kitchen',
    label: 'Kitchen Services',
    icon: '🍳',
    color: '#b45309',
    bg: '#fff7ed',
    border: '#fed7aa',
    count: 2,
    desc: 'Kitchen renovation, cabinet installation and kitchen tile works by experienced contractors.',
    terms: ['kitchen', 'cabinet', 'splashback'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'glass',
    label: 'Glass & Aluminium',
    icon: '🪟',
    color: '#7c3aed',
    bg: '#f5f3ff',
    border: '#ddd6fe',
    count: 6,
    desc: 'Glass railings, aluminium doors & windows, IPanel ceilings and gypsum works.',
    terms: ['glass', 'aluminium', 'aluminum', 'railing', 'ceiling', 'ipanel', 'gypsum', 'gate', 'fencing', 'door', 'window'],
    blogSlugs: ['how-to-choose-a-tiler', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'construction',
    label: 'Construction Services',
    icon: '🏗️',
    color: '#374151',
    bg: '#f8fafc',
    border: '#e2e8f0',
    count: 9,
    desc: 'Roofing, plastering, partition walls, concrete works and full construction services.',
    terms: ['roof', 'plaster', 'partition', 'water tank', 'concrete', 'masonry', 'carpentry', 'debris', 'demolition', 'cleaning', 'construction'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'outdoor',
    label: 'Outdoor Services',
    icon: '🌿',
    color: '#15803d',
    bg: '#f0fdf4',
    border: '#bbf7d0',
    count: 4,
    desc: 'Landscaping, swimming pool construction, paving, driveways and pergola structures.',
    terms: ['outdoor', 'landscape', 'garden', 'pool', 'paving', 'driveway', 'pergola', 'shade'],
    blogSlugs: ['large-format-tiles-guide', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'trades',
    label: 'Trades & More',
    icon: '🎨',
    color: '#c2410c',
    bg: '#fff7ed',
    border: '#fed7aa',
    count: 9,
    desc: 'House painting, electrical works, air conditioning, solar panels, CCTV and smart home installation.',
    terms: ['paint', 'lighting', 'wiring', 'electrical', 'air condition', 'solar', 'cctv', 'security', 'smart home', 'automation'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
]
