export const SERVICES = [
  { slug: 'bathroom-renovation',     icon: '🚿', label: 'Bathroom Renovation',      externalUrl: 'https://luxehome.lk', terms: ['Bathroom Renovation', 'Bathroom Reno', 'Bathroom Tiling'] },
  { slug: 'bathroom-plumbing',       icon: '🚽', label: 'Bathroom Plumbing',         terms: ['Bathroom Plumbing', 'Plumbing'] },
  { slug: 'bathroom-lighting',       icon: '💡', label: 'Bathroom Lighting',         terms: ['Bathroom Lighting', 'Lighting'] },
  { slug: 'shower-cubicle',          icon: '🚿', label: 'Shower Cubicle',            terms: ['Shower Cubicle', 'Shower Installation', 'Shower'] },
  { slug: 'bathroom-mirrors',        icon: '🪞', label: 'Bathroom Mirrors',          terms: ['Bathroom Mirrors', 'Mirror Installation'] },
  { slug: 'vanity-cupboard',         icon: '🗄️', label: 'Vanity Cupboard',           terms: ['Vanity Cupboard', 'Vanity'] },
  { slug: 'floor-tiling',            icon: '⬜', label: 'Floor Tiling',              terms: ['Floor Tiling', 'Flooring'] },
  { slug: 'large-format-tiling',     icon: '📏', label: 'Large Format Tiling',       terms: ['Large Format Tiling', 'Large Format'] },
  { slug: 'mosaic-tiling',           icon: '🎨', label: 'Mosaic Tiling',             terms: ['Mosaic Tiling', 'Mosaic'] },
  { slug: 'pool-tiling',             icon: '🏊', label: 'Pool Tiling',               terms: ['Pool Tiling', 'Swimming Pool'] },
  { slug: 'outdoor-tiling',          icon: '🏡', label: 'Outdoor Tiling',            terms: ['Outdoor Tiling', 'Outdoor', 'Exterior Tiling'] },
  { slug: 'tile-cutting-routering',  icon: '🧱', label: 'Tile Cutting & Routering',  terms: ['Tile Cutting', 'Routering', 'Tile Cutting & Routering'] },
  { slug: 'glass-railing',           icon: '✨', label: 'Glass Railing',             terms: ['Glass Railing', 'Railing', 'Glass Works'] },
  { slug: 'aluminium-glass-works',   icon: '🪟', label: 'Aluminium & Glass Works',   terms: ['Aluminium', 'Glass Works', 'Aluminium & Glass'] },
  { slug: 'ipanel-ceiling',          icon: '🏠', label: 'IPanel Ceiling',            terms: ['IPanel', 'IPanel Ceiling', 'Ceiling'] },
  { slug: 'house-lighting',          icon: '💡', label: 'House Lighting',            terms: ['House Lighting', 'House Lights'] },
  { slug: 'house-wiring',            icon: '⚡', label: 'House Wiring',             terms: ['House Wiring', 'Wiring', 'Electrical Wiring'] },
  { slug: 'electrical-repairs',      icon: '🔌', label: 'Electrical Repairs',        terms: ['Electrical Repairs', 'Electrical'] },
  { slug: 'waterproofing',           icon: '💧', label: 'Waterproofing',             terms: ['Waterproofing'] },
  { slug: 'landscaping-gardening',   icon: '🌿', label: 'Landscaping & Gardening',   terms: ['Landscaping', 'Gardening', 'Garden'] },
  { slug: 'granite-countertops',     icon: '🪨', label: 'Granite Countertops',       terms: ['Granite Countertops', 'Granite Works', 'Granite'] },
  { slug: 'aluminium-doors-windows', icon: '🚪', label: 'Aluminium Doors & Windows', terms: ['Aluminium Doors', 'Aluminium Windows', 'Doors & Windows'] },
  { slug: 'house-painting',          icon: '🎨', label: 'House Painting',             terms: ['House Painting', 'Wall Painting', 'Painting'] },
  { slug: 'furniture-painting',      icon: '🪑', label: 'Furniture Painting',         terms: ['Furniture Painting', 'Furniture Refinishing'] },
  { slug: 'carpentry-works',         icon: '🪵', label: 'Carpentry Works',            terms: ['Carpentry', 'Carpenter', 'Woodwork', 'Carpentry Works'] },
  { slug: 'debris-removal',          icon: '🚛', label: 'Debris Removal',             terms: ['Debris Removal', 'Waste Removal', 'Rubble Removal'] },
  { slug: 'demolition-work',         icon: '⚒️', label: 'Demolition Work',            terms: ['Demolition', 'Demolition Work', 'Breaking'] },
  { slug: 'site-cleaning',           icon: '🧹', label: 'Site Cleaning',              terms: ['Site Cleaning', 'Post-construction Cleaning', 'Cleaning'] },
  { slug: 'gypsum-ceiling',          icon: '🏛️', label: 'Gypsum Ceiling',             terms: ['Gypsum Ceiling', 'Gypsum', 'False Ceiling', 'Ceiling'] },
  // Phase 1
  { slug: 'kitchen-renovation',      icon: '🍳', label: 'Kitchen Renovation',         terms: ['Kitchen Renovation', 'Kitchen', 'Kitchen Tiles', 'Kitchen Reno'] },
  { slug: 'air-conditioning',        icon: '❄️', label: 'Air Conditioning',           terms: ['Air Conditioning', 'AC', 'HVAC', 'Air Con'] },
  { slug: 'roofing',                 icon: '🏚️', label: 'Roofing',                    terms: ['Roofing', 'Roof Repair', 'Roof Tiles', 'Roof'] },
  { slug: 'solar-panels',            icon: '☀️', label: 'Solar Panels',              terms: ['Solar Panels', 'Solar', 'Solar Power', 'Photovoltaic'] },
  { slug: 'plastering-skimming',     icon: '🪣', label: 'Plastering & Skimming',     terms: ['Plastering', 'Skimming', 'Plastering & Skimming', 'Render'] },
  { slug: 'gate-fencing',            icon: '🚧', label: 'Gate & Fencing',            terms: ['Gate', 'Fencing', 'Gate & Fencing', 'Fence', 'Gates'] },
  { slug: 'cctv-security',           icon: '📷', label: 'CCTV & Security',           terms: ['CCTV', 'Security', 'CCTV & Security', 'Security Camera', 'Surveillance'] },
  // Phase 2
  { slug: 'epoxy-flooring',          icon: '🟤', label: 'Epoxy Flooring',            terms: ['Epoxy Flooring', 'Epoxy', 'Epoxy Coating', 'Floor Coating'] },
  { slug: 'parquet-laminate',        icon: '🪵', label: 'Parquet / Laminate Flooring', terms: ['Parquet', 'Laminate', 'Laminate Flooring', 'Wood Flooring', 'Parquet Flooring'] },
  { slug: 'partition-walls',         icon: '🧱', label: 'Partition Walls',           terms: ['Partition Walls', 'Partition', 'Room Divider', 'Stud Wall'] },
  { slug: 'water-tank-installation', icon: '💦', label: 'Water Tank Installation',   terms: ['Water Tank', 'Water Tank Installation', 'Tank Installation'] },
  { slug: 'kitchen-cabinets',        icon: '🗄️', label: 'Kitchen Cabinets',          terms: ['Kitchen Cabinets', 'Cabinets', 'Cabinet Making', 'Joinery'] },
  { slug: 'concrete-masonry',        icon: '🏗️', label: 'Concrete & Masonry',        terms: ['Concrete', 'Masonry', 'Concrete & Masonry', 'Bricklaying', 'Blockwork'] },
  { slug: 'vinyl-flooring',          icon: '🟦', label: 'Vinyl Flooring',            terms: ['Vinyl Flooring', 'Vinyl', 'LVT', 'SPC Flooring', 'PVC Flooring'] },
  // Phase 3
  { slug: 'swimming-pool-construction', icon: '🏊', label: 'Swimming Pool Construction', terms: ['Swimming Pool', 'Pool Construction', 'Swimming Pool Construction', 'Pool Building'] },
  { slug: 'smart-home-automation',   icon: '🏠', label: 'Smart Home / Automation',   terms: ['Smart Home', 'Home Automation', 'Smart Lighting', 'Automation'] },
  { slug: 'paving-driveways',        icon: '🛤️', label: 'Paving & Driveways',        terms: ['Paving', 'Driveways', 'Paving & Driveways', 'Driveway', 'Patio Paving'] },
  { slug: 'pergola-shade',           icon: '⛱️', label: 'Pergola & Shade Structures', terms: ['Pergola', 'Shade Structure', 'Pergola & Shade', 'Gazebo', 'Awning'] },
  { slug: 'wall-tiling',             icon: '🧱', label: 'Wall Tiling',               terms: ['Wall Tiling', 'Wall Tiles', 'Feature Wall'] },
  { slug: 'pvc-ceiling',             icon: '🏠', label: 'PVC Ceiling',               terms: ['PVC Ceiling', 'PVC Board Ceiling', 'PVC'] },
]

export const SERVICES_GROUP_1 = SERVICES.slice(0, 8)
export const SERVICES_GROUP_2 = SERVICES.slice(8, 16)

export const HOME_GROUPS = [
  {
    key: 'bathroom',
    label: 'Bathroom',
    labelSi: 'නාන කාමර',
    icon: '🚿',
    viewAllHref: '/categories/bathroom',
    services: ['bathroom-renovation','shower-cubicle','vanity-cupboard','bathroom-mirrors','waterproofing','bathroom-plumbing','bathroom-lighting'],
  },
  {
    key: 'tiling',
    label: 'Tiling',
    labelSi: 'ටයිල් කිරීම',
    icon: '⬜',
    viewAllHref: '/categories/flooring',
    services: ['floor-tiling','wall-tiling','large-format-tiling','mosaic-tiling','tile-cutting-routering'],
  },
  {
    key: 'electrical',
    label: 'Electrical',
    labelSi: 'විදුලි',
    icon: '⚡',
    viewAllHref: '/providers?q=electrical',
    services: ['house-wiring','house-lighting','smart-home-automation'],
  },
  {
    key: 'ceiling',
    label: 'Ceiling & Interior',
    labelSi: 'සිවිලිම සහ අභ්‍යන්තර',
    icon: '🏠',
    viewAllHref: '/providers?q=ceiling',
    services: ['ipanel-ceiling','pvc-ceiling','gypsum-ceiling','house-painting'],
  },
  {
    key: 'outdoor',
    label: 'Outdoor',
    labelSi: 'බාහිර',
    icon: '🌿',
    viewAllHref: '/categories/outdoor',
    services: ['landscaping-gardening','paving-driveways','glass-railing'],
  },
]
